### ISSUE TITLE
Task的Status描述需要改为中文

### ISSUE THREAD

**Issue by CarlSome** [2019swsad/server#1]
如“start”改用"报名中"，其他的如：“进行中”(就是停止报名了)、“已结束”等。这样前端在获取任务状态后可以直接显示，不用额外处理。
注：如果这个改动会影响后端运作(如：可能影响状态判断相关函数的运行)，则通知前端不能进行改动，让前端自行处理。

**Comment by flyingmanPan** [comment]
后端存在问题,请前端自行转换
