### ISSUE TITLE
[低优先度]消息中心返回的消息内容需要优化

### ISSUE THREAD

**Issue by CarlSome** [2019swsad/server#18]
1、消息的title需要更明确
目前消息title为含糊的“您有新的消息”。应针对不同类型的消息，确定不同的title。可用title详情参考[issue#6](https://github.com/2019swsad/server/issues/6)
2、msg中，任务的名称应加双引号，方便阅读。如：您的任务“{task.title}”有新的参与者Carl_su2

**Comment by PeanutADi** [comment]
暂时先放一下 有很多别的功能先修好…
