### ISSUE TITLE
Need the API which can get specific user's info by uid

### ISSUE THREAD

**Issue by CarlSome** [2019swsad/server#5]
当发起请求的人不是Organizer，除了在原来的基础上返回"isOrganizer"字段以外，还需要附加以下发布者的信息。这样就不需要在前端多次发起请求，再次单独请求发布者的信息
return {
    organizerName: 
    credit:
    phone:
    profilePhotoURL:
}
In this stage,  we just need a static profile photo url like [this one](https://image.baidu.com/search/detail?ct=503316480&z=0&ipn=d&word=%E6%9D%A8%E8%B6%85%E8%B6%8A&step_word=&hs=0&pn=2&spn=0&di=202620&pi=0&rn=1&tn=baiduimagedetail&is=0%2C0&istype=0&ie=utf-8&oe=utf-8&in=&cl=2&lm=-1&st=undefined&cs=2755042241%2C4155348560&os=389116297%2C617134128&simid=0%2C0&adpicid=0&lpn=0&ln=1759&fr=&fmq=1560168459647_R&fm=&ic=undefined&s=undefined&hd=undefined&latest=undefined&copyright=undefined&se=&sme=&tab=0&width=undefined&height=undefined&face=undefined&ist=&jit=&cg=&bdtype=0&oriquery=&objurl=http%3A%2F%2Fimg0.pconline.com.cn%2Fpconline%2F1808%2F09%2F11581852_2_thumb.jpg&fromurl=ippr_z2C%24qAzdH3FAzdH3Fgjof_z%26e3Brv5gstgj_z%26e3Bv54_z%26e3BvgAzdH3F88cbAzdH3F88cb8bcd_z%26e3Bip4s&gsm=0&rpstart=0&rpnum=0&islist=&querylist=&force=undefined)

**Comment by flyingmanPan** [comment]
done in 32cf0e4, add API to do query rather than return in a single result
