### ISSUE TITLE
消息中心API

### ISSUE THREAD

**Issue by CarlSome** [2019swsad/server#6]
# 消息类型：
- 用户：
    - 有新的评价
    您收到了来自用户{name}的评价。
- 发布者：
    - 有新的报名者
    您发布的{title}任务已有新的报名者，请移步至“任务中心”查看任务报名详情。
    - 有报名者退出任务
    参与者{name}已退出您发布的{title}任务。
    - 有参与者完成任务
    参与者{name}已完成您发布的{title}任务。
- 参与者：
    - 报名资格被取消
    您报名{title}任务的资格已被发布者取消。
    - 候补被发布者转正；
    您报名{title}任务的候补资格已被转正，请抓紧时机去完成任务吧！
    - 任务已结束；
        - 您报名的{title}任务在未到开始时间前，已被发布者结束。
        - 您报名的{title}任务在未到达结束时间前，已被发布者提前结束。您将获得30%的酬劳作为补偿。
        - 您报名的{title}任务已到达任务结束时间，并被发布者手动结束任务。您还没有按时完成任务，下次记得抓紧时间喔！

**Comment by PeanutADi** [comment]
Done
